### PR TITLE
fix: don't swallow exceptions in LocalServerReceiver

### LINKED ISSUE #503: LocalServerReceiver uses PrintWriter
This causes it to swallow IOExceptions.

### PR DESCRIPTION
**Pull request by elharo**
fixes #503

### CODE REVIEW

File: google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java [hunk 1]
```diff
@@ -315,19 +315,19 @@ public void handle(HttpExchange httpExchange) throws IOException {
...
+      try (OutputStream os = exchange.getResponseBody()) {
+        exchange.sendResponseHeaders(HTTP_OK, 0);
+        headers.add("ContentType", "text/html");
+
+        OutputStreamWriter doc = new OutputStreamWriter(os, StandardCharsets.UTF_8);
+        doc.write("<html>");
+        doc.write("<head><title>OAuth 2.0 Authentication Token Received</title></head>");
+        doc.write("<body>");
+        doc.write("Received verification code. You may now close this window.");
+        doc.write("</body>");
```
Comment (chingor13) [inline google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java:327]: Not a huge deal as it's writing html, but do we want to preserve the newlines?

**Review by chingor13 — APPROVED** [review]
